server: 
    port: 8081
spring: 
    cloud:
        config: 
            server: 
                git:
                    default-label: multiple-instances
                    uri: https://github.com/AleexArteagaa/SpringBootPruebas
                    search-paths: config-data
    application:
        name: config-service

